### ISSUE TITLE
[Feature Request] Guide to update for react 17?

### ISSUE THREAD

**Issue by ahmadxgani** [creativetimofficial/argon-dashboard-chakra#3]
### What is your enhancement?
is there any guidance on how to update this package to reactjs 17?

I've been trying to figure it out but I'm still not sure how to do it, anyway this is a really great template!

**Comment by simmmpleweb** [comment]
Hello, @ahmadxgani ! Thanks for using our products! The product already is at React v17! If you are using v16, there are no breaking changes while migrating.
Regards, Vlad.
